# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-29 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('passwordverify', models.CharField(max_length=255)),
                ('birthdate', models.DateTimeField()),
                ('friended', models.ManyToManyField(related_name='_user_friended_+', to='foxes_app.User')),
            ],
        ),
    ]
